[workspace]
members = [
    "compiler",
    "midend",
    "backend",
    "runtime",
    "packages/spectra-contract",
    "packages/spectra-db",
    "packages/spectra-api",
    "tools/spectra-cli",
    "tools/spectra-interop",
    "tools/spectra-lsp",
]
resolver = "2"

[workspace.package]
edition = "2021"
