fn main() {
    // Embed the Windows application icon into spectralang.exe.
    // The icon file itself is generated by scripts/generate-icons.py from
    // the canonical SVG at assets/icon.svg.
    #[cfg(windows)]
    embed_resource::compile("assets/icon.rc", embed_resource::NONE);
}
